SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE DATABASE IF NOT EXISTS `ProjectI` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `ProjectI`;

DROP TABLE IF EXISTS `Questions`;
CREATE TABLE `Questions` (
  `QID` int(11) NOT NULL,
  `Question` varchar(100) NOT NULL,
  `RightAnswer` varchar(100) NOT NULL,
  `WrongAnswer1` varchar(100) NOT NULL,
  `WrongAnswer2` varchar(100) NOT NULL,
  `WrongAnswer3` varchar(100) NOT NULL,
  `QLevel` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `Users`;
CREATE TABLE `Users` (
  `UID` int(11) NOT NULL,
  `Name` varchar(100) DEFAULT NULL,
  `Score` int(11) DEFAULT NULL,
  `Date` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `Users` (`UID`, `Name`, `Score`, `Date`) VALUES
(1, 'BHTU', NULL, '2022-10-31 13:12:32'),
(2, 'npp', NULL, '2022-10-31 17:31:36');


ALTER TABLE `Questions`
  ADD PRIMARY KEY (`QID`);

ALTER TABLE `Users`
  ADD PRIMARY KEY (`UID`),
  ADD UNIQUE KEY `u_Name` (`Name`),
  ADD KEY `ixHighScore` (`Score`);


ALTER TABLE `Questions`
  MODIFY `QID` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `Users`
  MODIFY `UID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
